import { Inter } from 'next/font/google'
import { Noto_Sans } from 'next/font/google'
import Providers from './providers'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const noto = Noto_Sans({ subsets: ['latin'] })
export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='min-h-screen'>{children}</body>
		</html>
	)
}
